// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSite_EF.Data;

#nullable disable

namespace WebSite_EF.Migrations
{
    [DbContext(typeof(FotosDbContext))]
    [Migration("20251209200358_FotosMigration")]
    partial class FotosMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebSite_EF.Models.Foto", b =>
                {
                    b.Property<Guid>("FotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FotoId");

                    b.ToTable("Fotos");

                    b.HasData(
                        new
                        {
                            FotoId = new Guid("8f1843d7-92d1-4264-aa14-69b8ef235dac"),
                            Autor = "Sebastião Salgado",
                            Codigo = 123455,
                            Preco = 500.00m,
                            Titulo = "Terra"
                        },
                        new
                        {
                            FotoId = new Guid("a9e39a00-b8d2-4fe7-87e0-71d67a2a50ae"),
                            Autor = "Eduardo Gageiro ",
                            Codigo = 123466,
                            Preco = 100.00m,
                            Titulo = "Lisboa"
                        },
                        new
                        {
                            FotoId = new Guid("e2592c77-400d-4449-887f-83d7be49f261"),
                            Autor = "Eduardo Gageiro ",
                            Codigo = 123477,
                            Preco = 100.00m,
                            Titulo = "Lisboa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
