// <auto-generated />
using System;
using HospitEST_JuliaMizuguchiJulianaLeite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitEST_JuliaMizuguchiJulianaLeite.Migrations
{
    [DbContext(typeof(HospitEST_JuliaMizuguchiJulianaLeiteContext))]
    partial class HospitEST_JuliaMizuguchiJulianaLeiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Doctor_JMJL", b =>
                {
                    b.Property<Guid>("Id_JMJL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Hospital_JMJLId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_JMJL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PracticeYears_JMJL")
                        .HasColumnType("int");

                    b.Property<string>("Practice_JMJL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_JMJL");

                    b.HasIndex("Hospital_JMJLId");

                    b.ToTable("Doctor_JMJL");

                    b.HasData(
                        new
                        {
                            Id_JMJL = new Guid("b2a208c5-1c2c-4149-a678-51991ec0aa85"),
                            Hospital_JMJLId = new Guid("8b5491dc-7dfa-41f2-bc93-0e3f0fe66b5d"),
                            Name_JMJL = "Luis Silva",
                            PracticeYears_JMJL = 19,
                            Practice_JMJL = "Neurocirurgião"
                        },
                        new
                        {
                            Id_JMJL = new Guid("08cd38b0-8926-4a33-942a-eec6bcdaaadc"),
                            Hospital_JMJLId = new Guid("8b5491dc-7dfa-41f2-bc93-0e3f0fe66b5d"),
                            Name_JMJL = "Manuel Esteves",
                            PracticeYears_JMJL = 13,
                            Practice_JMJL = "Medicina Geral e Familiar"
                        },
                        new
                        {
                            Id_JMJL = new Guid("e2ec207c-1a71-45cb-a948-10b20074b336"),
                            Hospital_JMJLId = new Guid("ed8cfb19-c92f-4413-ac00-2a2bc41cafb2"),
                            Name_JMJL = "Sofia Feliz",
                            PracticeYears_JMJL = 4,
                            Practice_JMJL = "Pediatra"
                        },
                        new
                        {
                            Id_JMJL = new Guid("b6f98f2f-cecc-466c-a54a-7e23598c5fb7"),
                            Hospital_JMJLId = new Guid("ed8cfb19-c92f-4413-ac00-2a2bc41cafb2"),
                            Name_JMJL = "Miguel Neves",
                            PracticeYears_JMJL = 13,
                            Practice_JMJL = "Ortopedista"
                        });
                });

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Hospital_JMJL", b =>
                {
                    b.Property<Guid>("Id_JMJL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location_JMJL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_JMJL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_JMJL");

                    b.ToTable("Hospital_JMJL");

                    b.HasData(
                        new
                        {
                            Id_JMJL = new Guid("8b5491dc-7dfa-41f2-bc93-0e3f0fe66b5d"),
                            Location_JMJL = "Lisboa",
                            Name_JMJL = "Centro Hospitalar Lisboa Norte"
                        },
                        new
                        {
                            Id_JMJL = new Guid("ed8cfb19-c92f-4413-ac00-2a2bc41cafb2"),
                            Location_JMJL = "Setúbal",
                            Name_JMJL = "Centro Hospitalara de Setúbal"
                        });
                });

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Patient_JMJL", b =>
                {
                    b.Property<Guid>("Id_JMJL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth_JMJL")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Doctor_JMJLId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_JMJL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pathology_JMJL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_JMJL");

                    b.HasIndex("Doctor_JMJLId");

                    b.ToTable("Patient_JMJL");

                    b.HasData(
                        new
                        {
                            Id_JMJL = new Guid("5014f8bc-21e3-4dac-aa81-4743b8d7bebf"),
                            DateOfBirth_JMJL = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("b2a208c5-1c2c-4149-a678-51991ec0aa85"),
                            Name_JMJL = "Bernardo Pereira",
                            Pathology_JMJL = "Traumatismo Craniano"
                        },
                        new
                        {
                            Id_JMJL = new Guid("d4086df1-b10d-42d0-b1df-9db796924b26"),
                            DateOfBirth_JMJL = new DateTime(1957, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("b2a208c5-1c2c-4149-a678-51991ec0aa85"),
                            Name_JMJL = "Helena Porto",
                            Pathology_JMJL = "AVC"
                        },
                        new
                        {
                            Id_JMJL = new Guid("58c1465f-1a06-43e0-81fa-6d78b9a9dd78"),
                            DateOfBirth_JMJL = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("b2a208c5-1c2c-4149-a678-51991ec0aa85"),
                            Name_JMJL = "Otávio Campos",
                            Pathology_JMJL = "Tumor no cérebro"
                        },
                        new
                        {
                            Id_JMJL = new Guid("0c7fa654-2b21-4c7a-a7f4-24dbafdfc75e"),
                            DateOfBirth_JMJL = new DateTime(1984, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("08cd38b0-8926-4a33-942a-eec6bcdaaadc"),
                            Name_JMJL = "Ana Júlia Araújo",
                            Pathology_JMJL = "Gripe"
                        },
                        new
                        {
                            Id_JMJL = new Guid("795674c3-2ebe-499a-8a02-864a7be69651"),
                            DateOfBirth_JMJL = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("e2ec207c-1a71-45cb-a948-10b20074b336"),
                            Name_JMJL = "Maitê Alves",
                            Pathology_JMJL = "Asperger"
                        },
                        new
                        {
                            Id_JMJL = new Guid("98cac64c-71b4-4201-bb19-a63a3c0099af"),
                            DateOfBirth_JMJL = new DateTime(2004, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("b6f98f2f-cecc-466c-a54a-7e23598c5fb7"),
                            Name_JMJL = "António Campos",
                            Pathology_JMJL = "Perna partida"
                        },
                        new
                        {
                            Id_JMJL = new Guid("9d49481a-a989-414e-9546-3f3f190f95ee"),
                            DateOfBirth_JMJL = new DateTime(2005, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("b6f98f2f-cecc-466c-a54a-7e23598c5fb7"),
                            Name_JMJL = "Daniel Moreira",
                            Pathology_JMJL = "Cotovelo Rachado"
                        },
                        new
                        {
                            Id_JMJL = new Guid("768ae238-6063-4366-aace-78723320fb58"),
                            DateOfBirth_JMJL = new DateTime(2001, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doctor_JMJLId = new Guid("b6f98f2f-cecc-466c-a54a-7e23598c5fb7"),
                            Name_JMJL = "David Nogueira",
                            Pathology_JMJL = "Ombro deslocado"
                        });
                });

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Doctor_JMJL", b =>
                {
                    b.HasOne("HospitEST_JuliaMizuguchiJulianaLeite.Models.Hospital_JMJL", "Hospital_JMJL")
                        .WithMany("Doctors_JMJL")
                        .HasForeignKey("Hospital_JMJLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital_JMJL");
                });

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Patient_JMJL", b =>
                {
                    b.HasOne("HospitEST_JuliaMizuguchiJulianaLeite.Models.Doctor_JMJL", "Doctor_JMJL")
                        .WithMany("Patients_JMJL")
                        .HasForeignKey("Doctor_JMJLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor_JMJL");
                });

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Doctor_JMJL", b =>
                {
                    b.Navigation("Patients_JMJL");
                });

            modelBuilder.Entity("HospitEST_JuliaMizuguchiJulianaLeite.Models.Hospital_JMJL", b =>
                {
                    b.Navigation("Doctors_JMJL");
                });
#pragma warning restore 612, 618
        }
    }
}
