// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUT10_GRUPO_B.Data;

#nullable disable

namespace TUT10_GRUPO_B.Migrations
{
    [DbContext(typeof(MusicasDbContext))]
    [Migration("20251210133242_MusicasMigration")]
    partial class MusicasMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TUT10_GRUPO_B.Models.Musica_B", b =>
                {
                    b.Property<Guid>("Musica_BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor_B")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Duracao_B")
                        .HasColumnType("int");

                    b.Property<string>("Ficheiro_B")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo_B")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Musica_BId");

                    b.ToTable("Fotos");

                    b.HasData(
                        new
                        {
                            Musica_BId = new Guid("61d2efbe-1003-482b-a561-ed635a892f1e"),
                            Autor_B = "5 a Seco",
                            Duracao_B = 199,
                            Ficheiro_B = "/musicas/pensando bem.mp3",
                            Titulo_B = "Pensando Bem"
                        },
                        new
                        {
                            Musica_BId = new Guid("4f83abdb-1bc4-42b6-afc8-bf75c7ad511e"),
                            Autor_B = "Rubel",
                            Duracao_B = 422,
                            Ficheiro_B = "/musicas/quadro verde.mp3",
                            Titulo_B = "Quadro Verde"
                        },
                        new
                        {
                            Musica_BId = new Guid("d7606613-d319-40e7-9086-10e1201939d5"),
                            Autor_B = "Anavitória",
                            Duracao_B = 234,
                            Ficheiro_B = "/musicas/tenta acreditar.mp3",
                            Titulo_B = "Tenta Acreditar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
